version: "3.9"

services:
  app:
    build: .
    container_name: hockey_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # для локальной разработки
    env_file:
      - .env
    depends_on:
      - db
      - minio
    command: >
      sh -c "python init_s3.py && streamlit run streamlit_app.py --server.address=0.0.0.0"

  db:
    image: postgres:15
    container_name: hockey_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: hockey_minio
    ports:
      - "9000:9000"  # API (S3)
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
